// svg
export { default as Wave1 } from './wave1.svg';
export { default as Wave2 } from './wave2.svg';
export { default as Github } from './github_border.svg';
export { default as GithubLogo } from './github_logo.svg';
export { default as GithubLogoFill } from './github_logo_fill.svg';
export { default as ExternalLink } from './external-link.svg';
export { default as ExternalLinkGreen } from './external-link_green.svg';
export { default as ExternalLinkFill } from './external-link_fill.svg';
export { default as ExternalLinkMenu } from './external-link_menu.svg';
export { default as ExternalLinkMenuSm } from './external-link_menu_sm.svg';
export { default as Ellipse1 } from './ellipse1.svg';
export { default as Ellipse2 } from './ellipse2.svg';
export { default as SpaceONE } from './spaceone.svg';
export { default as SOneMan } from './soneman.svg';
export { default as Ellipse3 } from './ellipse3.svg';
export { default as Circle96 } from './Ellipse 96.svg';
export { default as Circle105 } from './Ellipse 105.svg';
export { default as Circle109 } from './Ellipse 109.svg';
export { default as Circle110 } from './Ellipse 110.svg';
export { default as Circle111 } from './Ellipse 111.svg';
export { default as Circle171 } from './Ellipse 171.svg';
export { default as GithubLogoMenu } from './github.svg';
export { default as GithubLogoMenuHover } from './github_hover.svg';
export { default as Universe } from './ouruniverse.svg';
export { default as Upcoming } from './upcoming.svg';
export { default as SOneManFooter } from './soneman_footer.svg';
export { default as UpIcon } from './upicon.svg';
export { default as Integrate } from './integrate.svg';
export { default as Improve } from './improve.svg';
export { default as Manage } from './manage.svg';
export { default as Mail } from './mail.svg';
export { default as MailHover } from './mail_hover.svg';
export { default as SOneMenu } from './sone_menu.svg';
export { default as Img1 } from './img1.svg';
export { default as Img2 } from './img2.svg';
export { default as Img3 } from './img3.svg';
export { default as Img4 } from './img4.svg';
export { default as Img5 } from './img5.svg';
export { default as DropdownBtn } from './dropdown_btn.svg';
export { default as DropdownCheck } from './dropdown_check.svg';
export { default as Loading } from './loading.svg';

// json
export { default as Cloud } from './cloud.json';
export { default as OpenAPI } from './openbox.json';
export { default as Plugin } from './plugin architecture.json';
export { default as PurplePlanet } from './purpleplanet.json';
export { default as Scroll } from './scroll.json';
export { default as Spaceman } from './spaceman.json';
export { default as Spaceship } from './spaceship.json';
export { default as SpinBlue } from './spin_blue.json';
export { default as SpinPurple } from './spin_purple.json';
export { default as SpinWhite } from './spin_white.json';
