export { default as Wave1 } from "./Vector 7.svg";
export { default as Wave2 } from "./Vector 8.svg";
export { default as Github } from "./Rectangle 114.svg";
export { default as GithubLogo } from "./Vector_gh.svg";
export { default as GithubLogo_fill } from "./Vector_gh_fill.svg";
export { default as ExternalLink } from "./ic_external-link v1.4.3.svg";
export { default as ExternalLink_fill } from "./ic_external-link v1.4.3_fill.svg";
export { default as Ellipse1 } from "./Group 2279.svg";
export { default as Ellipse2 } from "./Group 2280.svg";
export { default as SpaceONE } from "./Group 2264.svg";
export { default as SOneMan } from "./Group 2297.svg";
export { default as Ellipse3 } from "./Group 2417.svg";
export { default as Circle96 } from "./Ellipse 96.svg";
export { default as Circle105 } from "./Ellipse 105.svg";
export { default as Circle109 } from "./Ellipse 109.svg";
export { default as Circle110 } from "./Ellipse 110.svg";
export { default as Circle111 } from "./Ellipse 111.svg";
export { default as Circle101 } from "./Ellipse 101.svg";
export { default as Circle102 } from "./Ellipse 102.svg";
export { default as Circle171 } from "./Ellipse 171.svg";
export { default as ExternalLink_blue } from "./ic_external-link_menu.svg";
export { default as ExternalLink_blue_sm } from "./ic_external-link_menu_sm.svg";
export { default as GithubLogo_menu } from "./gnb_github.svg";
export { default as GithubLogo_menu_hover } from "./gnb_github_hover.svg";
export { default as Photo } from "./tabletgrosplandcb 1.svg";
export { default as Universe } from "./circlebg-1.svg";
export { default as MZ } from "./MZlogo-120.svg";
export { default as CNCF } from "./cncf-logo 1.svg";
export { default as Plugins } from "./plugins-2.svg";
export { default as Upcoming } from "./upcmoing-3.svg";
export { default as SOneMan_footer } from "./Group 2373.svg";
export { default as UpIcon } from "./Group 2481.svg";
export { default as Integrate } from "./Integrate_ic.svg";
export { default as Improve } from "./improve_ic.svg";
export { default as Manage } from "./manage_ic.svg";
