export { default as Background } from './Background';
export { default as Footer } from './Footer';
export { default as Menu } from './Menu';
export { default as Scroll1 } from './Scroll1';
export { default as Scroll2 } from './Scroll2';
export { default as Scroll3 } from './Scroll3';
export { default as Scroll4 } from './Scroll4';
export { default as Scroll5 } from './Scroll5';
export { default as Scroll6 } from './Scroll6';
