export { default as Wave1 } from "./Vector 7.svg";
export { default as Wave2 } from "./Vector 8.svg";
export { default as Github } from "./Rectangle 114.svg";
export { default as GithubLogo } from "./Vector.svg";
export { default as ExternalLink } from "./ic_external-link v1.4.3.svg";
export { default as Ellipse1 } from "./Group 2279.svg";
export { default as Ellipse2 } from "./Group 2280.svg";
export { default as SpaceONE } from "./Group 2264.svg";
export { default as SOneMan } from "./Group 2297.svg";
export { default as Ellipse3 } from "./Group 2417.svg";
export { default as Circle96 } from "./Ellipse 96.svg";
export { default as Circle105 } from "./Ellipse 105.svg";
export { default as Circle109 } from "./Ellipse 109.svg";
export { default as Circle110 } from "./Ellipse 110.svg";
export { default as Circle111 } from "./Ellipse 111.svg";
export { default as Circle101 } from "./Ellipse 101.svg";
export { default as Circle102 } from "./Ellipse 102.svg";
export { default as Circle171 } from "./Ellipse 171.svg";
export { default as ExternalLink_blue } from "./ic_external-link_menu.svg";
export { default as ExternalLink_blue_sm } from "./ic_external-link_menu_sm.svg";
export { default as GithubLogo_menu } from "./gnb_github.svg";
export { default as GithubLogo_menu_hover } from "./gnb_github_hover.svg";
export { default as Photo } from "./tabletgrosplandcb 1.svg";
export { default as Universe } from "./universe_circlebg.svg";
export { default as MZ } from "./mzlogo.svg";
export { default as CNCF } from "./cncflogo.svg";
export { default as Plugin1 } from "./spaceoneplugin-1.svg";
export { default as Plugin2 } from "./firstplugin-2.svg";
export { default as Plugin3 } from "./secondplugin-3.svg";
export { default as Plugin4 } from "./upcomingplugins-4.svg";
export { default as SOneMan_footer } from "./Group 2373.svg";
